package com.vbmvalidator.model;

public enum ErrorType {
    COST_SHARING_MISMATCH,
    PRIOR_AUTH_MISMATCH,
    PRIOR_AUTH_DETAILS_MISMATCH,
    DEDUCTIBLE_MISMATCH,
    SUPPLEMENTAL_BENEFIT_MISMATCH,
    COVERAGE_LIMIT_MISMATCH,
    MOOP_STATEMENT_MISSING,
    GUIDELINE_VIOLATION,
    INN_OON_MISMATCH,
    REFERRAL_REQUIRED_MISMATCH,
    FORMATTING_ERROR,
    MISSING_DATA
} 
